[gcp_service_account]
type = "service_account"
project_id = "bank-statement-analysis-420306"
private_key_id = "220845a76fb164b229a8d448bc37c6043c6e0417"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDAd8rwE/fM8Be3
Qea6gPESn/uhA2HcSSMaNg8uF1zvSP2ieKvsOUmq/3S+D5sjbukJ6gktGI5Wgxb8
PjqGXq7PLGS1sO4totNbyiDw3o1YczUFsPYiOfwFYDnNwjDZWLCWyZ6bKeNxMMAa
C01hSz9bMuMpJ7YZctZgjXuOWQ0Z7KTjCiR1+z2lrHBIMBl9f5e1+LUy+kTYYbBH
bdPNeMvAHn4+v8reobydrJwEmxREU8wtuGc/x16b0IIloxY0WDngMT7U9wO9R2Q3
JU9iqwkO7BiHFocE3fFGbhK/L5YvsZ3aM+y6+vL4bUSXC/iJ6STKrjFI7uAkYE0/
JdcFVqhdAgMBAAECggEAUWf5qnzPoVtltInHtNfH32hSbmJ3WEyI79OwrP6NvNnj
CX6/vOzoJ07gSmlgZWbKY3qdQfkybw4IQU1yxJW0m4T73cuFmkDV4+uE7kw7fY9Q
/GTCXmynF4EBQfGiZrO4ETcbAib//8auYfWo13+TvxexdB1LTM1BNlpxSZ6Jx44P
ZHwhHbNsUbbH7c9Dksbb9xn1V1YH1abNmcfwohiE2re9K3r4tFKcIChq0Jr5+UWl
rKWlOlN96YsmbgZO3CM7uEAoER1lrAiqEaBwXxBaPoBSxSPlSloSQgDiCEAKgmKX
yZFaPV0f9S7hPPqOlPCSCSVMFLaf/9rBqT/L9/sVEwKBgQDtmH/FB89/QLUtjldM
WxxMuUJck8j6uWx5532UDqtfddrdHrMXJBlsNqMeV5EDTI1qJhmrAPnMgKMB05Uh
eNdmMjlDepH8REkQdV1lwSCmGgoJhgsdK4AAjTYi7JLoFVy5Y4sV4rL9FQHqVZWb
+t0ifyKhYi/6nlOnJvhLhzgY6wKBgQDPYGoP12mIZzMsgAzUcshNd5uvJmUfGwD8
NHjH7go72lzl/vjIxfoREYRgiJNLQ44AX0d/xucYWL18Uescqqzuhbep7Bsqp8pm
e83sxDLpLPbYTaQpoO0dhzsROKFDV7RQu6MjXy3KAhwo8dnGc53O3axmqSJ04nJt
V89eqC5x1wKBgAyUfH9kMHpeZLlqxfiHAnKVhIv+Ty/nTXUO6rlCJZTCWrpGe9kH
0kjGg9CBdm4kSYCLT+ScAp3vWbIpD8Zb7Zu9oQaPoNcojm3OqQlQNnhU/J8Qd9ot
iXN+BpXGzOh46RXvzVd1T2DTEezkZy2BFOBUtvKwjjXI2EkLaS4mlLPNAoGAdeqb
xHA3WNFdntMc+Hxf+vSk+L37R+mh8MahWwW2mfv7UOhfbEJug+ATBpUCNAywpPOI
g1aFNynWbOdjqgQ+ms479goEFIgeJZIGMLgLPt1LawkS7HzN9zla09sAj3tCU5mu
FMHdFn2Gp52FuDsro2IW0rUfm5jbeeMxTeCRsDcCgYEAhymiiq4KXRlBMoJtKBbg
B5B4uMs571FPhuwqCZhc3dVHhq7UVdE9qrnDtcW2OatOIps3f1PiuwkuiwIBDI5R
tpOQTFI9gmIvQUuHAxRgwsKLWnObnwOYqfUbVQo03NPOLsJ90p7LK+RIIafDhuJx
lpRVXbDF2RdAvX8wJTfoVB4=
-----END PRIVATE KEY-----
"""
client_email = "document-ai-account@bank-statement-analysis-420306.iam.gserviceaccount.com"
client_id = "114356059928539670857"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/document-ai-account%40bank-statement-analysis-420306.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
